# 廠商後台測試環境: https://cweb.pay2go.com
# 信用卡測試卡號:
# 4000-2222-2222-2222
# 4000-1322-2222-2222
default: &default
  merchant_id: MS31606011
  hash_key: Iz4L2iEpW0vdF4cXaqug4Izqeuq0R7QA
  hash_iv: GVlIe08b0EpFIBDS
  url: https://ccore.spgateway.com/MPG/mpg_gateway
  notify_url: https://requestb.in/1f6vbr11

development:
  <<: *default

staging:
  <<: *default

test:
  <<: *default

production:
  <<: *default
